service: ddns-gcp-functions

frameworkVersion: ">=1.64.1 <2.0.0"

provider:
  name: google
  runtime: python37
  region: ${file(../conf/setting.json):GCP_REGION}
  project: ${file(../conf/setting.json):PROJECT_ID}
  credentials: ${file(../conf/setting.json):GOOGLE_APPLICATION_CREDENTIALS}
  environment:
    SETTING_PATH: ${file(../conf/setting.json):SETTING_PATH}

functions:
  a_set:
    handler: a_set
    events:
      - http: a_set

package:
  exclude:
    - ./**
  include:
    - ddns_gcp_functions/*.py
    - main.py
    - package.json
    - requirements.txt

plugins:
  - serverless-google-cloudfunctions
